-- insert into member (city, street, zipcode, name) values ('서울턱별시 강남구', '테헤란로', '12-1', '참깨');
--
-- insert into member (city, street, zipcode, name) values ('인천 남덩구', '남덩로', '1032-12', '꾸꾸까까');
--
-- insert into member (city, street, zipcode, name) values ('부싼 해운대구', '해운로', '554-33', '뭐라카노');
--
--
-- insert into item (name, price, stock_quantity, author, isbn, dtype) values ('알고리즘 문제 해결 전략1', 33000, 15, '구종만', '123-123', 'B');
--
-- insert into item (name, price, stock_quantity, artist, etc, dtype) values ('IU 미니 앨범', 28000, 10, 'IU', '작곡가,작사가: WhyWhale', 'A');
--
-- insert into item (name, price, stock_quantity, actor, director, dtype) values ('트랜스포머<달의 어둠>', 10000, 30, '옵티머스프라임,범블비', '마이클 베이', 'M');
--
-- insert into item (name, price, stock_quantity, artist, etc, dtype) values ('Rollin', 27000, 10, '브레이브걸스', '작곡가,작사가: 용감한 형제', 'A');
--
-- insert into item (name, price, stock_quantity, author, isbn, dtype) values ('알고리즘 문제 해결 전략2', 33000, 15, '구종만', '123-1234', 'B');
--
-- insert into item (name, price, stock_quantity, actor, director, dtype) values ('트랜스포머<사라진 시대>', 10000, 30, '옵티머스프라임,범블비', '마이클 베이', 'M');